### ISSUE TITLE
Retrying "upload.SaveBigFilePart" due to TimeoutError()

### ISSUE THREAD

**Issue by lucasgabrisouza** [apenasrr/zimatise#2]
![image](https://user-images.githubusercontent.com/114821067/193416236-d78c07d5-b6a3-4529-82f6-cfc2b301b701.png)

**Hi, how can I solve this? This is the last version of zimatise, I already checked my connection, I guess it's ok!**

https://user-images.githubusercontent.com/114821067/193416408-8ee2af87-7829-4fd3-8f4e-6c63db388cc9.mp4

![image](https://user-images.githubusercontent.com/114821067/193416502-ebf72a85-4890-41cc-a6e1-38e5541f4e5b.png)

**Comment by apenasrr** [comment]
Instability of your connection. nothing related to zimatise
